name: carros_full_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  path: ^1.8.2
  sqflite: ^2.2.8+4
  sqflite_common: ^2.4.5+1
  sqflite_common_ffi: ^2.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
